version: "3"
services:

  ui:
    build: ../ui
    container_name: bi_ui
    depends_on:
      - db
      - dashboard
      - data_source
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - VITE_APP_API_URL=http://dashboard:4010/api
      - VITE_APP_USER_URL=http://dashboard:4010/api
      - VITE_APP_DS_URL=http://data_source:4011/api
    networks:
      - bi

  dashboard:
    build: ../backend/dashboard
    container_name: bi_dashboard
    depends_on:
      - db
    expose:
      - "4010"
    ports:
      - "4010:4010"
    environment:
      - PG_DSN=postgres://postgres:postgres@db:5433/bi?sslmode=disable
      - DASHBOARD_PORT=4010
      - DATA_SOURCE_RECALL_URL=http://localhost:4011/api/ds/recall
    networks:
      - bi

  data_source:
    build: ../backend/data_source
    container_name: bi_data_source
    depends_on:
      - db
    expose:
      - "4011"
    ports:
      - "4011:4011"
    environment:
      - PG_DSN=postgres://postgres:postgres@db:5433/bi?sslmode=disable
      - DATA_SOURCE_PORT=4011
    networks:
      - bi
    extra_hosts:
      - "localhost:192.168.1.55"

  db:
    image: postgres
    container_name: bi_db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bi-db-data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    command: -p 5433
    networks:
      - bi

  # prometheus

  # grafana

volumes:
  bi-db-data:

networks:
  bi:
    driver: bridge
    external: true