version: "3"
services:

  dashboard:
    build: ../backend/dashboard
    container_name: bi_dashboard
    depends_on:
      - db
    expose:
      - "4010"
    ports:
      - "4010:4010"
    environment:
      - PG_DSN=postgres://postgres:postgres@db:5433/bi?sslmode=disable
      - DASHBOARD_PORT=4010
    networks:
      - bi

  data_storage:
    build: ../backend/data_storage
    container_name: bi_data_storage
    depends_on:
      - db
    expose:
      - "4011"
    ports:
      - "4011:4011"
    environment:
      - PG_DSN=postgres://postgres:postgres@db:5433/bi?sslmode=disable
      - DATA_SOURCE_PORT=4011
    networks:
      - bi
#
#  gateway:
#    build: ../backend/gateway
#    container_name: bi_gateway
#    depends_on:
#      - db
#    expose:
#      - "3012"
#    ports:
#      - "3012:3012"
#    environment:
#      - PG_DSN=postgres://postgres:postgres@db:5432/bi?sslmode=disable
#      - SERVER_PORT=3012
#    networks:
#      - bi

  db:
    image: postgres
    container_name: bi_db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bi-db-data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    command: -p 5433
    networks:
      - bi

volumes:
  bi-db-data:

networks:
  bi:
    driver: bridge